In [5]:
import sys,os
import numpy as np
#import matplotlib
#matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
%pylab qt


Populating the interactive namespace from numpy and matplotlib


In [133]:
normal_child = np.load('/Users/jannisborn/Dropbox/GitHub/LSTM/Models/childlex/normal_run_6/metrics.npz')
lds_child    = np.load('/Users/jannisborn/Dropbox/GitHub/LSTM/Models/childlex/lds_run_7/metrics.npz')
normal_fibel = np.load('/Users/jannisborn/Dropbox/GitHub/LSTM/Models/fibel/normal_run_1/metrics.npz')
lds_fibel    = np.load('/Users/jannisborn/Dropbox/GitHub/LSTM/Models/fibel/lds_run_2/metrics.npz')

epochs = np.arange(500)
perf_x = np.arange(50)
xticks_e = np.arange(50,501,50)
xticks_p = np.arange(5,51,5)
xticklabels = xticks_e
print(xticks_p)
print(xticklabels)

[ 5 10 15 20 25 30 35 40 45 50]
[ 50 100 150 200 250 300 350 400 450 500]


In [81]:
normal_child_train = normal_data_f['trainPerf']
testPerf_n = normal_data_f['testPerf']
lds_ratio_n = normal_data_f['lds_ratio']
corr_ratio_n = normal_data_f['corr_ratio']
lds_loss_n = normal_data_f['lds_loss']
reg_loss_n = normal_data_f['reg_loss']


trainPerf_l = lds_data_f['trainPerf']
testPerf_l = lds_data_f['testPerf']
lds_ratio_l = lds_data_f['lds_ratio']
corr_ratio_l = lds_data_f['corr_ratio']
lds_loss_l = lds_data_f['lds_loss']
reg_loss_l = lds_data_f['reg_loss']


In [135]:
# Fibel - Training - Token accuracy plot 
plt.plot(perf_x,normal_fibel['trainPerf'][:-1,0],'--ob',label='Regular writing module')
plt.plot(perf_x,lds_fibel['trainPerf'][:-1,0],'--c',label='LdS writing module')
plt.plot(perf_x, normal_fibel['trainPerf'][:-1,3],'--r',label='Regular reading module')
plt.plot(perf_x,lds_fibel['trainPerf'][:-1,3],'--m',label='LdS reading module')
plt.title("Fibel dataset - Token accuracy - Training data")
plt.ylabel("Accuracy")
plt.xlabel("Epochs")
plt.xticks(xticks_p,xticklabels)
plt.legend(loc=4)
plt.axvline(25)
plt.show()

In [139]:
# Childlex - Writing - Training - Token accuracy plot 
plt.plot(perf_x,normal_child['trainPerf'][:-1,1],'--ob',label='Regular writing module')
plt.plot(perf_x,lds_child['trainPerf'][:-1,1],'--c',label='LdS writing module')
plt.plot(perf_x, normal_child['trainPerf'][:-1,4],'--r',label='Regular reading module')
plt.plot(perf_x,lds_child['trainPerf'][:-1,4],'--m',label='LdS reading module')
plt.title("Childlex dataset - Word accuracy - Training data")
plt.ylabel("Accuracy")
plt.xlabel("Epochs")
plt.xticks(xticks_p,xticklabels)
plt.legend(loc=4)
plt.axvline(25)
plt.ylim([0.5, 1.05])
plt.show()

In [88]:
plt.plot(epochs_n,lds_loss_l,'-b',label='lds_l')
plt.plot(epochs_n,lds_loss_n,'-c',label='lds_n')
plt.plot(epochs_n, reg_loss_l,'-r',label='reg_l')
plt.plot(epochs_n,reg_loss_n,'-m',label='reg_n')
plt.ylim([0, 0.35])

# for lds network the loss  
plt.legend(loc=4)
plt.show()

In [86]:
el = np.arange(101)
en = np.arange(51)

# Performance columns indices
# 0 - write_token_acc
# 1 - write_word_acc
# 2 - write_old_acc
# 3 - read_token_acc
# 4 - read_word_acc
# 5 - read_old_acc



plt.plot(el,testPerf_l[:,3],'--b',label='LdS - Training - Reading - Token')
plt.plot(en,testPerf_n[:,3],'--c',label='Regular - Training - Reading - Token')
#plt.ylim([0.2, 0.5])



# for lds network the loss  
plt.legend(loc=4)
plt.show()

ValueError: x and y must have same first dimension, but have shapes (101,) and (51,)

In [99]:
plot(np.arange(50),normal_fibel['trainPerf'][:-1,1])

In [117]:
a = np.arange(2,10,2)
a

array([2, 4, 6, 8])